language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:~/.cargo/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin

install:
  # Roswell
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - ros install fukamachi/rove
  # cargo
  - curl https://sh.rustup.rs -sSf | sh -s -- -y

script:
  - make test

notifications:
  slack: changelibgirl:yDKtlmsMuwbIIsHD4jRig3Zt
